#! /bin/sh

$Drive01= /mnt/Drive01
$Drive02= /mnt/Drive02
$Drive03= /mnt/Drive03
$Drive04= /mnt/Drive04
$Drive05= /mnt/Drive05
$Drive06= /mnt/Drive06
$Drive07= /mnt/Drive07
$Drive08= /mnt/Drive08
$Drive09= /mnt/Drive09
$Drive10= /mnt/Drive10
$Drive11= /mnt/Drive11
$Drive12= /mnt/Drive12
$Drive13= /mnt/Drive13
$Drive14= /mnt/Drive14
$Drive15= /mnt/Drive15


echo Starting now. If there have been many files added, this may take a long time!

cd "$Drive01"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive01.log

echo Drive01 has finished. View the log at /var/log/plex-file-check/Drive01.log

cd "$Drive02"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive02.log

echo Drive02 has finished. View the log at /var/log/plex-file-check/Drive02.log

cd "$Drive03"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive03.log

echo Drive03 has finished. View the log at /var/log/plex-file-check/Drive03.log

cd "$Drive04"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive04.log

echo Drive04 has finished. View the log at /var/log/plex-file-check/Drive04.log

cd "$Drive05"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive05.log

echo Drive05 has finished. View the log at /var/log/plex-file-check/Drive05.log

cd "$Drive06"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive06.log

echo Drive06 has finished. View the log at /var/log/plex-file-check/Drive06.log

cd "$Drive07"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive07.log

echo Drive07 has finished. View the log at /var/log/plex-file-check/Drive07.log

cd "$Drive08"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive08.log

echo Drive08 has finished. View the log at /var/log/plex-file-check/Drive08.log

cd "$Drive09"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive09.log

echo Drive09 has finished. View the log at /var/log/plex-file-check/Drive09.log

cd "$Drive10"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive10.log

echo Drive10 has finished. View the log at /var/log/plex-file-check/Drive10.log

cd "$Drive11"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive11.log

echo Drive11 has finished. View the log at /var/log/plex-file-check/Drive11.log

cd "$Drive11"

cd "$Drive12"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive12.log

echo Drive12 has finished. View the log at /var/log/plex-file-check/Drive12.log

cd "$Drive13"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive13.log

echo Drive13 has finished. View the log at /var/log/plex-file-check/Drive13.log

cd "$Drive14"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive14.log

echo Drive14 has finished. View the log at /var/log/plex-file-check/Drive14.log

cd "$Drive15"

find . -ctime -5 -type f -iname "*.mkv" ! -iname "*.mp4" ! -iname "*.mov" -exec  ~/plex-file-check/checkfile.py \{\} \; > /var/log/plex-file-check/Drive15.log

echo Drive15 has finished. View the log at /var/log/plex-file-check/Drive15.log

